### ISSUE TITLE
Unexpected ComboBox default filter lookup behaviour

### ISSUE THREAD

**Issue by alanrsoares** [nikgraf/belle#135]
Hey guys. I'm using Belle's ComboBox as replacement to @JedWatson's react-select.
Some issues I've spotted regarding the default behaviour:
- Default filter lookup only caters Option.value, not the text (which would be the user expected behaviour)
- Default filter lookup expect that Option.value is a string, when the most common use cases is mapping ids (numbers most of the time) as values.

**Comment by nikgraf** [comment]
@alanrsoares Good find!

Sounds better to search through the Option children instead of value. If we switch the default behaviour the second issue should be solved as we. I guess the tricky part here will be to get a text representation in case the there are nested children. My first guess is that we will need a helper function to traverse through the children and compile a text version e.g.

```
<Option>
  He<span>ll</span>o World!
  <div>
    This is a <b>Test</b>
  </div>
</Option>
``` 

should result in `Hello World!This is a Test`

@jpuri What do you think?

**Comment by jpuri** [comment]
I think its not wrong to use value for comparison, coz value is what is ultimately copied to combobox. We have different text for user to be able to put additional information about the option. And you can always make value same as text.

And I am not able to think of a filter for numeric value, I think its good the way it is right now. Can you suggest some filter which can cater to numeric value, btw this combobox allows custom filters also.

**Comment by nikgraf** [comment]
Hmm, I didn't think of the case that we actually copy the value into the input. That makes things a bit more tricky.

I definitely can see the use-case where you want to have IDs in the value rather than the actual value. I must say right now the ComboBox is not very well designed for this use-case. Actually I will need to later today as well.

Some thoughts on how it could work:

```
<ComboBox>
  <Option value={ 1234 } inputText={ Croatia }>
    <img src="/path/to/croatia-image" />Croatia (Special Deal)
  </Option>
  <Option value={ 1235 } inputText={ France }>
    <img src="/path/to/france-image" />France (Best Price)
  </Option>
</ComboBox>
```

In this case we could take the inputText and apply it to the input when selecting an Option with they mouse for example.

What also would be useful/necessary is to make onUpdate only be called when a perfect match happened. `inputProps={ onUpdate: this.onInputUpdate }` would still allow to read out whenever a character in the input changed or a option has been selected and the input was updated.

These are a few API changes and it complicates things a bit more. On the other side it would help to support the use-case of selecting from a pre-defined list. I will sleep over it and have look tomorrow again. What are your thoughts @jpuri @alanrsoares ?

**Comment by jpuri** [comment]
Hey @nikgraf , @alanrsoares ,

Might be I do not understand the use case you guys have.
I am wondering combobox at the end is input, why like ```<select/>``` it would need to input something different than value.

**Comment by nikgraf** [comment]
@jpuri I almost have it. A lot of people don't use see/use it as an Input like the Google search rather then a Select with better UX for large sets of data. Think like the use-case of typeahead https://twitter.github.io/typeahead.js/. When someone searches for a Twitter user the onChange with typing is not helpful. What you want to know is if the user selected with typing or mouse click is in the list of the available Options you provided. It's important because if you have a match you can redirect to the profile. If it's not a match you don't want to do anything and let the user continue it's search.

**Comment by alanrsoares** [comment]
@nikgraf, that's exactly the point. In my use case I managed to get it
working given the current constraints. But it felt quite hacky. Having to
manually tell on the onUpdate callback whether that was an input change or
an option being selected.

**Comment by jpuri** [comment]
Hey @nikgraf , @alanrsoares ,

I get your point here. onBlur can help us know when the user is finally done with changing the value. But it would be useful to have additional callbacks that will be triggered when user selects some value from options or use hint to change value. :+1: (complex :smile: )

Do you think we still need a value different from text in input box (like ids) for filtering ?

**Comment by jpuri** [comment]
I think different value from inputText can be useful for situations like user wants more complex filtering and not the default one we provide.

But then what should we send back to the user in callbacks (onUpdate, onBlur). In addition since we are using React's ```<input>``` for combobox. What will be value of that input, it will not be possible to have a value different from what it shows.

**Comment by nikgraf** [comment]
@alanrsoares Just had a call with @jpuri and we came up with an idea:

Instead of allowing to change the behaviour of value we could add an optional identifier which we provide in the onUpdate callback. We also consider adding an extra callback in case a exact match happened.

```
<Option value="France" identifier={ 1234 }>
    <img src="/path/to/france-image" />France (Best Price)
</Option>


onChange({
  value: "France",
  identifier: 1234
})
```

**Comment by nikgraf** [comment]
Hey @alanrsoares, just right now we released a new version of Belle allowing you to pass in via the onUpdate callback get out identifiers. In addition you can check if the values was matching an Options.

See all the changes here: https://github.com/nikgraf/belle/blob/master/CHANGELOG.md#added

Here an examples how to use it:
```
<ComboBox onUpdate={ (event) => { if (event.isMatchingOption) { _chooseOption(event.identifier) }}}>
  <Option value="Alaska" identifier={ 1 }>Alaska</Option>
  <Option value="California"  identifier={ 2 }>California</Option>
</ComboBox>
```

What do you think? Does this work for you?
